export const verbTenses = {
  get: 'got',
  take: 'took',
  grab: 'grabbed',
  pickup: 'picked up',
  pick: 'picked',
  examine: 'examined',
  inspect: 'inspected',
  check: 'checked',
  go: 'went',
  move: 'moved',
  walk: 'walked',
  head: 'headed',
  travel: 'traveled',
  run: 'ran',
  sprint: 'sprinted',
  jog: 'jogged',
  use: 'used',
  utilize: 'utilized',
  activate: 'activated',
  operate: 'operated',
  open: 'opened',
  close: 'closed',
  turn: 'turned',
  push: 'pushed',
  pull: 'pulled',
  flip: 'flipped',
  press: 'pressed',
  unlock: 'unlocked',
  look: 'looked',
  survey: 'surveyed',
  scan: 'scanned',
  see: 'saw',
  view: 'viewed',
  watch: 'watched',
  observe: 'observed',
};

export function getPastTense(verb) {
  return verbTenses[verb.toLowerCase()] || `${verb}ed`;
}
